min_password_length: 6
max_name_length: 50
max_email_length: 255
gravatar_size: 50
gravatar_small_size: 30
per_page: 10
remember_me_checked: 1
time_expired: 2
micropost_max_length: 140
max_picture_size: 1
resize_width_limit: 400
resize_height_limit: 400
